#!/usr/bin/env Rscript
# Usage: Rscript differential.R counts.tsv metadata.tsv numerator denominator out normalization [spikein.tsv]
a <- commandArgs(TRUE)
alpha <- as.numeric(Sys.getenv('CUTTAG_ALPHA','0.05'))
lfc <- as.numeric(Sys.getenv('CUTTAG_LFC','1'))
min_count <- as.numeric(Sys.getenv('CUTTAG_MIN_COUNT','10'))
stopifnot(is.finite(alpha),alpha>0,alpha<1,is.finite(lfc),lfc>=0,is.finite(min_count),min_count>=0)
if(length(a)<7 || !a[6] %in% c('conventional','spikein')) stop('counts metadata numerator denominator NEW_output conventional|spikein [spikein_table] review.json')
if(length(a)!=if(a[6]=='spikein') 8 else 7)stop('Expected explicit model review as final argument')
if(a[3]==a[4])stop('Contrast conditions must differ')
script_arg<-grep('^--file=',commandArgs(FALSE),value=TRUE)[1]
checker<-file.path(dirname(normalizePath(sub('^--file=','',script_arg))), 'check_model_review.py')
check_args<-c(checker,'--review',tail(a,1),'--counts',a[1],'--metadata',a[2],'--numerator',a[3],'--denominator',a[4],'--normalization',a[6],'--alpha',alpha,'--lfc',lfc,'--min-count',min_count)
if(a[6]=='spikein')check_args<-c(check_args,'--spikein',a[7])
if(system2(Sys.getenv('CUTTAG_PYTHON','python3'),shQuote(check_args))!=0)stop('Model review failed')
suppressPackageStartupMessages(library(DESeq2))
x <- read.delim(a[1],check.names=FALSE); m <- read.delim(a[2],check.names=FALSE)
stopifnot(all(c('peak_id','chrom','start','end') %in% names(x)),all(c('sample_id','biological_sample_id','condition','replicates_confirmed') %in% names(m)))
if(anyNA(m[,c('sample_id','biological_sample_id','condition','replicates_confirmed')]) || any(m$sample_id=='') || any(m$biological_sample_id==''))stop('Missing sample identities')
if(any(!m$condition %in% a[3:4]))stop('Metadata includes samples outside requested contrast')
if(anyNA(x[,c('peak_id','chrom','start','end')]) || anyDuplicated(names(x)) || any(x$peak_id=='') || any(x$start<0) || any(x$end<=x$start) || any(x$start!=floor(x$start)) || any(x$end!=floor(x$end)))stop('Invalid count matrix coordinates/IDs')
if(!setequal(setdiff(names(x),c('peak_id','chrom','start','end')),m$sample_id))stop('Count columns differ from metadata')
stopifnot(!anyDuplicated(m$sample_id),!anyDuplicated(m$biological_sample_id),all(m$replicates_confirmed==TRUE),all(table(factor(m$condition,levels=a[3:4]))>=2),!anyDuplicated(x$peak_id),all(m$sample_id %in% names(x)))
k <- as.matrix(x[,m$sample_id,drop=FALSE]);stopifnot(all(is.finite(k)),all(k>=0),all(k==floor(k)),max(k)<=.Machine$integer.max)
storage.mode(k)<-'integer';rownames(k)<-x$peak_id;rownames(m)<-m$sample_id
m$condition<-factor(m$condition,levels=c(a[4],a[3])); keep<-rowSums(k)>=min_count
if(!any(keep)) stop('No peaks pass count filter')
dds<-DESeqDataSetFromMatrix(k[keep,,drop=FALSE],m,~condition)
if(a[6]=='spikein') {
 s<-read.delim(a[7]);stopifnot(all(c('sample_id','spikein_fragments','calibration_accepted') %in% names(s)),!anyDuplicated(s$sample_id),setequal(s$sample_id,m$sample_id));s<-s[match(m$sample_id,s$sample_id),];stopifnot(identical(s$sample_id,m$sample_id),all(is.finite(s$spikein_fragments)),all(s$spikein_fragments>0),all(s$calibration_accepted==TRUE))
 sizeFactors(dds)<-s$spikein_fragments/exp(mean(log(s$spikein_fragments)))
} else if(a[6]!='conventional') stop('Unknown normalization')
if(dir.exists(a[5])) stop('Output exists; choose new model directory')
dir.create(a[5],recursive=TRUE)
write_tsv<-function(z,n) write.table(z,file.path(a[5],n),sep='\t',quote=FALSE,row.names=FALSE)
write_tsv(data.frame(peak_id=x$peak_id,retained=keep),'filter_decisions.tsv')
write_tsv(m,'metadata.tsv')
invisible(file.copy(tail(a,1),file.path(a[5],'review.json')))
writeLines(normalizePath(tail(a,1)),file.path(a[5],'review_source.txt'))
dds<-DESeq(dds,quiet=TRUE);res<-as.data.frame(results(dds,contrast=c('condition',a[3],a[4]),alpha=alpha))
z<-cbind(x[match(rownames(res),x$peak_id),c('peak_id','chrom','start','end')],res)
z$direction<-'not_significant';sig<-!is.na(z$padj)&z$padj<alpha&abs(z$log2FoldChange)>=lfc
z$direction[sig & z$log2FoldChange>0]<-'gain';z$direction[sig & z$log2FoldChange<0]<-'loss'
write_tsv(z,'complete.tsv');write_tsv(z[z$direction=='gain',],'gain.tsv');write_tsv(z[z$direction=='loss',],'loss.tsv')
write_tsv(data.frame(sample_id=colnames(dds),size_factor=sizeFactors(dds)),'size_factors.tsv')
write_tsv(data.frame(peak_id=rownames(dds),counts(dds,normalized=TRUE),check.names=FALSE),'normalized_counts.tsv')
saveRDS(dds,file.path(a[5],'model.rds'));capture.output(sessionInfo(),file=file.path(a[5],'sessionInfo.txt'))
pdf(file.path(a[5],'MA.pdf'));plotMA(results(dds,contrast=c('condition',a[3],a[4])),main=paste(a[3],'/',a[4]));dev.off()
writeLines(c(paste('Contrast:',a[3],'/',a[4]),paste('Normalization:',a[6]),paste('Design: ~ condition; min_total_count=',min_count,'; FDR<',alpha,'; abs(log2FC)>=',lfc),'Peak signal differences do not constitute RNA expression differences.'),file.path(a[5],'METHODS.txt'))
